version: '3'
services:
  mysql-server:
    image: mysql:5.7
    container_name: mysql_1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'test'
      MYSQL_PASS: '123456'
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
    ports:
      - "3306:3306"
    command: [
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    ]

