version: '2'
services:
  kafka-server-node0:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka-host0
    container_name: kafka-node0
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.6.100:9092
      KAFKA_ADVERTISED_HOST_NAME: 192.168.6.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk-server-node0:2181,zk-server-node1:2181,zk-server-node2:2181
      JMX_PORT: 9999 
    volumes:
    - ./logs/node0/logs:/kafka
    external_links: # 连接本compose文件以外的container
    - zk-server-node0
    - zk-server-node1
    - zk-server-node2
    networks:
      default:
        ipv4_address: 172.23.0.14

  kafka-server-node1:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka-host1
    container_name: kafka-node1
    ports:
    - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.6.100:9093 
      KAFKA_ADVERTISED_HOST_NAME: 192.168.6.100
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zk-server-node0:2181,zk-server-node1:2181,zk-server-node2:2181
      JMX_PORT: 9988
    volumes:
    - ./logs/node1/logs:/kafka
    external_links:  
    - zk-server-node0
    - zk-server-node1
    - zk-server-node2
    networks:
      default:
        ipv4_address: 172.23.0.15

  kafka-server-node2:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka-host2
    container_name: kafka-node2
    ports:
    - "9094:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.6.100:9094
      KAFKA_ADVERTISED_HOST_NAME: 192.168.6.100
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zk-server-node0:2181,zk-server-node1:2181,zk-server-node2:2181
      JMX_PORT: 9977
    volumes:
    - ./logs/node2/logs:/kafka
    external_links:  # 连接本compose文件以外的container
    - zk-server-node0
    - zk-server-node1
    - zk-server-node2
    networks:
      default:
        ipv4_address: 172.23.0.16

  kafka-manager-server:
    image: sheepkiller/kafka-manager:latest
    restart: always
    container_name: kafa-manager
    hostname: kafka-manager-hostname
    ports:
      - "9002:9000"
    links:            # 连接本compose文件创建的container
      - kafka-server-node0
      - kafka-server-node1
      - kafka-server-node2
    external_links:   # 连接本compose文件以外的container
      - zk-server-node0
      - zk-server-node1
      - zk-server-node2
    environment:
      ZK_HOSTS: zk-server-node0:2181,zk-server-node1:2181,zk-server-node2:2181
      KAFKA_BROKERS: kafka-server-node0:9092,kafka-server-node1:9093,kafka-server-node2:9094
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    networks:
      default:
        ipv4_address: 172.23.0.10

networks:
  default:
    external:   # 使用已创建的网络
      name: zookeeper_network